In [5]:
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(".")
import j1j2_2d_block

### Creating the model, then diagonalizing it using two different methods

In [6]:
width=3
depth=4
J1=1.0
J2=0.5
model1=j1j2_2d_block.J1J2_2D(width,depth,J1,J2,0)



First, we diagonalize the block using the slow, high memory method.

In [7]:
model1.create_matrix_block()
model1.diagonalize()

Dense matrix needs  128.0  MiB of memory.


Next, lets check and make sure that the lowest 3 eigenvectors all have norm 1 and are orthogonal.

In [8]:
eigvs=model1.eigenvectors[0:3]
print(np.inner(eigvs.conj(),eigvs))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]


Now lets try the faster, lower memory method for calculating only the kth lowest eigenvalues.

In [9]:
model2=j1j2_2d_block.J1J2_2D(width,depth,J1,J2,0)
model2.create_matrix_block()
model2.sparse_calc_spectrum(k=3)

We can try to diagonalize a larger model width and width = 4 and depth = 4. This would take 32 Gb using the dense matrix method.

In [10]:
width=4
depth=4
model2=j1j2_2d_block.J1J2_2D(width,depth,J1,J2,0)
model2.create_matrix_block()
model2.sparse_calc_spectrum(k=3)